x-common-env: &fider-env
  GO_ENV: ${env_string}
  # Public Host Name
  BASE_URL: ${base_url}

  # Connection string to the PostgreSQL database
  DATABASE_URL: ${database_url}

  # Generate a secure secret, for example using https://jwtsecret.com
  JWT_SECRET: ${jwt_secret}

  # From which account e-mails will be sent
  EMAIL_NOREPLY: noreply@yourdomain.com

  ###
  # EMAIL
  # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* or EMAIL_AWSSES_* is required
  ###

  # EMAIL_MAILGUN_API: key-yourkeygoeshere
  # EMAIL_MAILGUN_DOMAIN: yourdomain.com
  # EMAIL_MAILGUN_REGION: US

  EMAIL_SMTP_HOST: ${mailhog_host}
  EMAIL_SMTP_PORT: ${mailhog_smtp_port}
  # EMAIL_SMTP_USERNAME: user@yourdomain.com
  # EMAIL_SMTP_PASSWORD: 
  # EMAIL_SMTP_ENABLE_STARTTLS: 'true'

  # EMAIL_AWSSES_REGION: us-east-1
  # EMAIL_AWSSES_ACCESS_KEY_ID: youraccesskeygoeshere
  # EMAIL_AWSSES_SECRET_ACCESS_KEY: yoursecretkeygoeshere  
  LOG_LEVEL: ${fider_log_level}
  DISABLE_EMAIL_NOTIFICATIONS: true
  LOG_CONSOLE: true
  LOG_SQL: ${fider_sql_log_level}
  LOG_FILE: false
  LOG_FILE_OUTPUT: logs/output.log  

  DATABASE_MAX_IDLE_CONNS: ${FIDER_IDLE_CONNS}
  DATABASE_MAX_OPEN_CONNS: ${FIDER_OPEN_CONNS}


  GOOGLE_ANALYTICS: ${GOOGLE_ANALYTICS}
  GOOGLE_ADSENSE: ${GOOGLE_ADSENSE}

  METRICS_ENABLED: ${METRICS_ENABLED}
  METRICS_PORT: 4000



x-common-build-args: &common-build-args
  DOCKER_USER_GID: ${DOCKER_USER_GID}
  DOCKER_USER_UID: ${DOCKER_USER_UID}

services:
  fider:
    build:
      context: ./
      dockerfile: Dockerfile
      args: *common-build-args
    image: ${IMAGE_REGISTRY:-ghcr.io}/${github_repo}:${image_tag:-latest}
    environment: *fider-env
    ports:
      - "${http_port}:3000" 
      - "${METRICS_PORT}:4000" 
    hostname: tarkov-community-${env_string}
    #container_name: fider
    restart: always
    networks:
      bw-services:
        aliases:
          - fider

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "${mailhog_web_port}:8025"
      - "${mailhog_smtp_port}:1025"
    networks:
      bw-services:
        aliases:
          - fider      
  postgres:
    #container_name: fider_pgdev
    restart: always
    image: postgres:12
    command: >
      postgres
      -c max_connections=${PG_MAX_CONNS}
      -c shared_buffers=${PG_SHARED_BUFFERS}
      -c effective_cache_size=${PG_CACHE}
      -c work_mem=${PG_WORK_MEM}
      -c maintenance_work_mem=${PG_MAINTENANCE_WORK_MEM}
      -c checkpoint_completion_target=0.9
      -c wal_buffers=${PG_WAL_BUFF} 
    volumes:
      - pgdev-data:/var/lib/postgresql/data
    ports:
      - "${postgres_dev_db_port}:5432"
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    networks:
      bw-services:
        aliases:
          - fider      
  pgadmin:
    image: dpage/pgadmin4
    #container_name: pgadmin4
    restart: always
    ports:
      - "${pgadmin_port}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_email}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      bw-services:
        aliases:
          - fider      

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${cloudflared}
    networks:
      bw-services:
        aliases:
          - fider       
    

  # pgtest:
  #   container_name: fider_pgtest
  #   restart: always
  #   image: postgres:12
  #   ports:
  #     - "${postgres_test_db_port}:5432"
  #   environment:
  #     POSTGRES_USER: fider_test
  #     POSTGRES_PASSWORD: fider_test_pw
  # s3test:
  #   container_name: fider_s3test
  #   restart: always
  #   image: minio/minio:RELEASE.2021-07-27T02-40-15Z
  #   ports:
  #     - "${minio_port}:9000"
  #     - "${minio2_port}:9001"
  #   volumes:
  #     - s3test-data:/data
  #   environment:
  #     MINIO_ACCESS_KEY: s3user
  #     MINIO_SECRET_KEY: s3user-s3cr3t
  #   command: server /data --console-address ":${minio2_port}"

volumes:
  pgdev-data:
  pgadmin-data:
#  s3test-data:

networks:
  bw-services:
    external: true
    name: bw-services
