import { SessionPermissions, UserPermissions } from "@fider/models"

export const noSessionPermissions: SessionPermissions = {
  readSettings: false,
  manageProfanity: false,
  createUsers: false,
  viewDesignSystem: false,
  manageAPIKeys: false,
  changeOwnEmail: false,
  enableEmailNotifications: false,
  manageSettings: false,
  manageContentSettings: false,
  managePages: false,
  managePageTopics: false,
  manageNavigation: false,
  manageTags: false,
  manageMembers: false,
  manageReports: false,
  manageReportReasons: false,
  manageQueue: false,
  manageArchive: false,
  manageResponses: false,
  readResponses: false,
  manageSponsorship: false,
  manageWebhooks: false,
  manageAuthentication: false,
  manageInvitations: false,
  manageBilling: false,
  manageFiles: false,
  exportBackup: false,
  readProfiles: false,
  editUserProfiles: false,
  moderateUsers: false,
  deleteUserModeration: false,
  expireUserModeration: false,
  blockUsers: false,
  changeUserRoles: false,
  changeUserVisualRoles: false,
  readUserEmails: false,
  createPosts: false,
  editPosts: false,
  deletePosts: false,
  respondToPosts: false,
  lockPosts: false,
  moderatePosts: false,
  tagPosts: false,
  viewPostVotes: false,
}

export const noUserPermissions: UserPermissions = {
  readProfile: false,
  editName: false,
  editAvatar: false,
  block: false,
  moderate: false,
  deleteModeration: false,
  expireModeration: false,
  changeRole: false,
  changeVisualRole: false,
}
