// Auto-generated by scripts/build-sprites.js - DO NOT EDIT
// Run: npm run build:sprites

interface SpriteSymbol {
  id: string
  viewBox: string
}

export const ccAmex: SpriteSymbol = { id: "cc-amex", viewBox: "0 0 780 500" }
export const ccDiners: SpriteSymbol = { id: "cc-diners", viewBox: "0 0 780 500" }
export const ccDiscover: SpriteSymbol = { id: "cc-discover", viewBox: "0 0 780 500" }
export const ccGeneric: SpriteSymbol = { id: "cc-generic", viewBox: "0 0 780 500" }
export const ccJcb: SpriteSymbol = { id: "cc-jcb", viewBox: "0 0 780 500" }
export const ccMaestro: SpriteSymbol = { id: "cc-maestro", viewBox: "0 0 780 500" }
export const ccMastercard: SpriteSymbol = { id: "cc-mastercard", viewBox: "0 0 780 500" }
export const ccUnionpay: SpriteSymbol = { id: "cc-unionpay", viewBox: "0 0 780 500" }
export const ccVisa: SpriteSymbol = { id: "cc-visa", viewBox: "0 0 780 500" }
export const faCaretdown: SpriteSymbol = { id: "fa-caretdown", viewBox: "0 0 320 512" }
export const faCaretup: SpriteSymbol = { id: "fa-caretup", viewBox: "0 0 320 512" }
export const heroiconsAdjustments: SpriteSymbol = { id: "heroicons-adjustments", viewBox: "0 0 24 24" }
export const heroiconsArchive: SpriteSymbol = { id: "heroicons-archive", viewBox: "0 0 24 24" }
export const heroiconsArrowLeft: SpriteSymbol = { id: "heroicons-arrow-left", viewBox: "0 0 24 24" }
export const heroiconsArrowUpDown: SpriteSymbol = { id: "heroicons-arrow-up-down", viewBox: "0 0 24 24" }
export const heroiconsBell: SpriteSymbol = { id: "heroicons-bell", viewBox: "0 0 24 24" }
export const heroiconsBlock: SpriteSymbol = { id: "heroicons-block", viewBox: "0 0 24 24" }
export const heroiconsCalendar: SpriteSymbol = { id: "heroicons-calendar", viewBox: "0 0 24 24" }
export const heroiconsChatAlt2: SpriteSymbol = { id: "heroicons-chat-alt-2", viewBox: "0 0 24 24" }
export const heroiconsCheckCircle: SpriteSymbol = { id: "heroicons-check-circle", viewBox: "0 0 24 24" }
export const heroiconsCheck: SpriteSymbol = { id: "heroicons-check", viewBox: "0 0 24 24" }
export const heroiconsChevronDown: SpriteSymbol = { id: "heroicons-chevron-down", viewBox: "0 0 24 24" }
export const heroiconsChevronUp: SpriteSymbol = { id: "heroicons-chevron-up", viewBox: "0 0 24 24" }
export const heroiconsCog: SpriteSymbol = { id: "heroicons-cog", viewBox: "0 0 24 24" }
export const heroiconsCreditCard: SpriteSymbol = { id: "heroicons-credit-card", viewBox: "0 0 24 24" }
export const heroiconsDocumentText: SpriteSymbol = { id: "heroicons-document-text", viewBox: "0 0 24 24" }
export const heroiconsDotsHorizontal: SpriteSymbol = { id: "heroicons-dots-horizontal", viewBox: "0 0 24 24" }
export const heroiconsDownload: SpriteSymbol = { id: "heroicons-download", viewBox: "0 0 24 24" }
export const heroiconsDuplicate: SpriteSymbol = { id: "heroicons-duplicate", viewBox: "0 0 24 24" }
export const heroiconsEnvelope: SpriteSymbol = { id: "heroicons-envelope", viewBox: "0 0 24 24" }
export const heroiconsExclamationCircle: SpriteSymbol = { id: "heroicons-exclamation-circle", viewBox: "0 0 24 24" }
export const heroiconsExclamation: SpriteSymbol = { id: "heroicons-exclamation", viewBox: "0 0 24 24" }
export const heroiconsExternalLink: SpriteSymbol = { id: "heroicons-external-link", viewBox: "0 0 24 24" }
export const heroiconsEye: SpriteSymbol = { id: "heroicons-eye", viewBox: "0 0 24 24" }
export const heroiconsFilter: SpriteSymbol = { id: "heroicons-filter", viewBox: "0 0 24 24" }
export const heroiconsFlag: SpriteSymbol = { id: "heroicons-flag", viewBox: "0 0 24 24" }
export const heroiconsIdentification: SpriteSymbol = { id: "heroicons-identification", viewBox: "0 0 24 24" }
export const heroiconsInbox: SpriteSymbol = { id: "heroicons-inbox", viewBox: "0 0 24 24" }
export const heroiconsInformationCircle: SpriteSymbol = { id: "heroicons-information-circle", viewBox: "0 0 24 24" }
export const heroiconsKey: SpriteSymbol = { id: "heroicons-key", viewBox: "0 0 24 24" }
export const heroiconsLightBulb: SpriteSymbol = { id: "heroicons-light-bulb", viewBox: "0 0 24 24" }
export const heroiconsLink: SpriteSymbol = { id: "heroicons-link", viewBox: "0 0 24 24" }
export const heroiconsLock: SpriteSymbol = { id: "heroicons-lock", viewBox: "0 0 24 24" }
export const heroiconsMail: SpriteSymbol = { id: "heroicons-mail", viewBox: "0 0 24 24" }
export const heroiconsMenu: SpriteSymbol = { id: "heroicons-menu", viewBox: "0 0 24 24" }
export const heroiconsMuted: SpriteSymbol = { id: "heroicons-muted", viewBox: "0 0 24 24" }
export const heroiconsPencilAlt: SpriteSymbol = { id: "heroicons-pencil-alt", viewBox: "0 0 24 24" }
export const heroiconsPhotograph: SpriteSymbol = { id: "heroicons-photograph", viewBox: "0 0 24 24" }
export const heroiconsPlay: SpriteSymbol = { id: "heroicons-play", viewBox: "0 0 24 24" }
export const heroiconsPlusCircle: SpriteSymbol = { id: "heroicons-plus-circle", viewBox: "0 0 24 24" }
export const heroiconsPlus: SpriteSymbol = { id: "heroicons-plus", viewBox: "0 0 24 24" }
export const heroiconsPluscircle: SpriteSymbol = { id: "heroicons-pluscircle", viewBox: "0 0 24 24" }
export const heroiconsRefresh: SpriteSymbol = { id: "heroicons-refresh", viewBox: "0 0 24 24" }
export const heroiconsSearch: SpriteSymbol = { id: "heroicons-search", viewBox: "0 0 24 24" }
export const heroiconsSelector: SpriteSymbol = { id: "heroicons-selector", viewBox: "0 0 24 24" }
export const heroiconsShieldcheck: SpriteSymbol = { id: "heroicons-shieldcheck", viewBox: "0 0 24 24" }
export const heroiconsSmile: SpriteSymbol = { id: "heroicons-smile", viewBox: "0 0 24 24" }
export const heroiconsSparklesOutline: SpriteSymbol = { id: "heroicons-sparkles-outline", viewBox: "0 0 24 24" }
export const heroiconsSpeakerphone: SpriteSymbol = { id: "heroicons-speakerphone", viewBox: "0 0 24 24" }
export const heroiconsStar: SpriteSymbol = { id: "heroicons-star", viewBox: "0 0 24 24" }
export const heroiconsTag: SpriteSymbol = { id: "heroicons-tag", viewBox: "0 0 24 24" }
export const heroiconsThumbsdown: SpriteSymbol = { id: "heroicons-thumbsdown", viewBox: "0 0 24 24" }
export const heroiconsThumbsup: SpriteSymbol = { id: "heroicons-thumbsup", viewBox: "0 0 24 24" }
export const heroiconsTrash: SpriteSymbol = { id: "heroicons-trash", viewBox: "0 0 24 24" }
export const heroiconsUpload: SpriteSymbol = { id: "heroicons-upload", viewBox: "0 0 24 24" }
export const heroiconsUsers: SpriteSymbol = { id: "heroicons-users", viewBox: "0 0 24 24" }
export const heroiconsVolumeOff: SpriteSymbol = { id: "heroicons-volume-off", viewBox: "0 0 24 24" }
export const heroiconsVolumeOn: SpriteSymbol = { id: "heroicons-volume-on", viewBox: "0 0 24 24" }
export const heroiconsXCircle: SpriteSymbol = { id: "heroicons-x-circle", viewBox: "0 0 24 24" }
export const heroiconsX: SpriteSymbol = { id: "heroicons-x", viewBox: "0 0 24 24" }
export const reactionAdd: SpriteSymbol = { id: "reaction-add", viewBox: "0 0 24 24" }
export const swipeCards: SpriteSymbol = { id: "swipe-cards", viewBox: "0 0 24 24" }
export const undrawEmpty: SpriteSymbol = { id: "undraw-empty", viewBox: "0 0 24 24" }
export const undrawNoData: SpriteSymbol = { id: "undraw-no-data", viewBox: "0 0 647.63626 632.17383" }
export const undrawPost: SpriteSymbol = { id: "undraw-post", viewBox: "0 0 843.57946 640.51678" }
export const undrawPublicDiscussion: SpriteSymbol = { id: "undraw-public-discussion", viewBox: "0 0 894.13386 586.58369" }

// Re-export all icons as a map for dynamic lookup
export const icons: Record<string, SpriteSymbol> = {
  "cc-amex": ccAmex,
  "cc-diners": ccDiners,
  "cc-discover": ccDiscover,
  "cc-generic": ccGeneric,
  "cc-jcb": ccJcb,
  "cc-maestro": ccMaestro,
  "cc-mastercard": ccMastercard,
  "cc-unionpay": ccUnionpay,
  "cc-visa": ccVisa,
  "fa-caretdown": faCaretdown,
  "fa-caretup": faCaretup,
  "heroicons-adjustments": heroiconsAdjustments,
  "heroicons-archive": heroiconsArchive,
  "heroicons-arrow-left": heroiconsArrowLeft,
  "heroicons-arrow-up-down": heroiconsArrowUpDown,
  "heroicons-bell": heroiconsBell,
  "heroicons-block": heroiconsBlock,
  "heroicons-calendar": heroiconsCalendar,
  "heroicons-chat-alt-2": heroiconsChatAlt2,
  "heroicons-check-circle": heroiconsCheckCircle,
  "heroicons-check": heroiconsCheck,
  "heroicons-chevron-down": heroiconsChevronDown,
  "heroicons-chevron-up": heroiconsChevronUp,
  "heroicons-cog": heroiconsCog,
  "heroicons-credit-card": heroiconsCreditCard,
  "heroicons-document-text": heroiconsDocumentText,
  "heroicons-dots-horizontal": heroiconsDotsHorizontal,
  "heroicons-download": heroiconsDownload,
  "heroicons-duplicate": heroiconsDuplicate,
  "heroicons-envelope": heroiconsEnvelope,
  "heroicons-exclamation-circle": heroiconsExclamationCircle,
  "heroicons-exclamation": heroiconsExclamation,
  "heroicons-external-link": heroiconsExternalLink,
  "heroicons-eye": heroiconsEye,
  "heroicons-filter": heroiconsFilter,
  "heroicons-flag": heroiconsFlag,
  "heroicons-identification": heroiconsIdentification,
  "heroicons-inbox": heroiconsInbox,
  "heroicons-information-circle": heroiconsInformationCircle,
  "heroicons-key": heroiconsKey,
  "heroicons-light-bulb": heroiconsLightBulb,
  "heroicons-link": heroiconsLink,
  "heroicons-lock": heroiconsLock,
  "heroicons-mail": heroiconsMail,
  "heroicons-menu": heroiconsMenu,
  "heroicons-muted": heroiconsMuted,
  "heroicons-pencil-alt": heroiconsPencilAlt,
  "heroicons-photograph": heroiconsPhotograph,
  "heroicons-play": heroiconsPlay,
  "heroicons-plus-circle": heroiconsPlusCircle,
  "heroicons-plus": heroiconsPlus,
  "heroicons-pluscircle": heroiconsPluscircle,
  "heroicons-refresh": heroiconsRefresh,
  "heroicons-search": heroiconsSearch,
  "heroicons-selector": heroiconsSelector,
  "heroicons-shieldcheck": heroiconsShieldcheck,
  "heroicons-smile": heroiconsSmile,
  "heroicons-sparkles-outline": heroiconsSparklesOutline,
  "heroicons-speakerphone": heroiconsSpeakerphone,
  "heroicons-star": heroiconsStar,
  "heroicons-tag": heroiconsTag,
  "heroicons-thumbsdown": heroiconsThumbsdown,
  "heroicons-thumbsup": heroiconsThumbsup,
  "heroicons-trash": heroiconsTrash,
  "heroicons-upload": heroiconsUpload,
  "heroicons-users": heroiconsUsers,
  "heroicons-volume-off": heroiconsVolumeOff,
  "heroicons-volume-on": heroiconsVolumeOn,
  "heroicons-x-circle": heroiconsXCircle,
  "heroicons-x": heroiconsX,
  "reaction-add": reactionAdd,
  "swipe-cards": swipeCards,
  "undraw-empty": undrawEmpty,
  "undraw-no-data": undrawNoData,
  "undraw-post": undrawPost,
  "undraw-public-discussion": undrawPublicDiscussion
}
