// Code generated by scripts/generate-bus-dispatch.go. DO NOT EDIT.
//go:generate go run ../scripts/generate-bus-dispatch.go

package bus

import (
	"context"
	"fmt"

	"github.com/Spicy-Bush/fider-tarkov-community/app/models/cmd"
	"github.com/Spicy-Bush/fider-tarkov-community/app/models/query"
)

var cActivateBillingSubscriptionHandler func(context.Context, *cmd.ActivateBillingSubscription) error
var cActivateTenantHandler func(context.Context, *cmd.ActivateTenant) error
var cAddNewCommentHandler func(context.Context, *cmd.AddNewComment) error
var cAddNewNotificationHandler func(context.Context, *cmd.AddNewNotification) error
var cAddNewPostHandler func(context.Context, *cmd.AddNewPost) error
var cAddNewTagHandler func(context.Context, *cmd.AddNewTag) error
var cAddPageCommentHandler func(context.Context, *cmd.AddPageComment) error
var cAddSubscriberHandler func(context.Context, *cmd.AddSubscriber) error
var cAddVoteHandler func(context.Context, *cmd.AddVote) error
var cArchivePostHandler func(context.Context, *cmd.ArchivePost) error
var cAssignReportHandler func(context.Context, *cmd.AssignReport) error
var cAssignTagHandler func(context.Context, *cmd.AssignTag) error
var cBlockUserHandler func(context.Context, *cmd.BlockUser) error
var cBulkArchivePostsHandler func(context.Context, *cmd.BulkArchivePosts) error
var cCancelBillingSubscriptionHandler func(context.Context, *cmd.CancelBillingSubscription) error
var cChangeUserEmailHandler func(context.Context, *cmd.ChangeUserEmail) error
var cChangeUserRoleHandler func(context.Context, *cmd.ChangeUserRole) error
var cChangeUserVisualRoleHandler func(context.Context, *cmd.ChangeUserVisualRole) error
var cCreateCannedResponseHandler func(context.Context, *cmd.CreateCannedResponse) error
var cCreatePageHandler func(context.Context, *cmd.CreatePage) error
var cCreatePageTagHandler func(context.Context, *cmd.CreatePageTag) error
var cCreatePageTopicHandler func(context.Context, *cmd.CreatePageTopic) error
var cCreateReportHandler func(context.Context, *cmd.CreateReport) error
var cCreateReportReasonHandler func(context.Context, *cmd.CreateReportReason) error
var cCreateTenantHandler func(context.Context, *cmd.CreateTenant) error
var cDeleteAllPushSubscriptionsHandler func(context.Context, *cmd.DeleteAllPushSubscriptions) error
var cDeleteBlobHandler func(context.Context, *cmd.DeleteBlob) error
var cDeleteCannedResponseHandler func(context.Context, *cmd.DeleteCannedResponse) error
var cDeleteCommentHandler func(context.Context, *cmd.DeleteComment) error
var cDeleteCurrentUserHandler func(context.Context, *cmd.DeleteCurrentUser) error
var cDeleteImageFileHandler func(context.Context, *cmd.DeleteImageFile) error
var cDeleteImageFileReferencesHandler func(context.Context, *cmd.DeleteImageFileReferences) error
var cDeleteMuteHandler func(context.Context, *cmd.DeleteMute) error
var cDeletePageHandler func(context.Context, *cmd.DeletePage) error
var cDeletePageTagHandler func(context.Context, *cmd.DeletePageTag) error
var cDeletePageTopicHandler func(context.Context, *cmd.DeletePageTopic) error
var cDeletePushSubscriptionHandler func(context.Context, *cmd.DeletePushSubscription) error
var cDeletePushSubscriptionByEndpointHandler func(context.Context, *cmd.DeletePushSubscriptionByEndpoint) error
var cDeleteReportHandler func(context.Context, *cmd.DeleteReport) error
var cDeleteReportReasonHandler func(context.Context, *cmd.DeleteReportReason) error
var cDeleteTagHandler func(context.Context, *cmd.DeleteTag) error
var cDeleteWarningHandler func(context.Context, *cmd.DeleteWarning) error
var cExpireMuteHandler func(context.Context, *cmd.ExpireMute) error
var cExpireWarningHandler func(context.Context, *cmd.ExpireWarning) error
var cGenerateCheckoutLinkHandler func(context.Context, *cmd.GenerateCheckoutLink) error
var cGetWebhookPropsHandler func(context.Context, *cmd.GetWebhookProps) error
var cHTTPRequestHandler func(context.Context, *cmd.HTTPRequest) error
var cLockExpiredTenantsHandler func(context.Context, *cmd.LockExpiredTenants) error
var cLockPostHandler func(context.Context, *cmd.LockPost) error
var cMarkAllNotificationsAsReadHandler func(context.Context, *cmd.MarkAllNotificationsAsRead) error
var cMarkNotificationAsReadHandler func(context.Context, *cmd.MarkNotificationAsRead) error
var cMarkPostAsDuplicateHandler func(context.Context, *cmd.MarkPostAsDuplicate) error
var cMuteUserHandler func(context.Context, *cmd.MuteUser) error
var cParseOAuthRawProfileHandler func(context.Context, *cmd.ParseOAuthRawProfile) error
var cPreviewWebhookHandler func(context.Context, *cmd.PreviewWebhook) error
var cPublishScheduledPagesHandler func(context.Context, *cmd.PublishScheduledPages) error
var cPurgeExpiredNotificationsHandler func(context.Context, *cmd.PurgeExpiredNotifications) error
var cPurgeReadNotificationsHandler func(context.Context, *cmd.PurgeReadNotifications) error
var cRefreshPageEmbeddedDataHandler func(context.Context, *cmd.RefreshPageEmbeddedData) error
var cRefreshPostStatsHandler func(context.Context, *cmd.RefreshPostStats) error
var cRegenerateAPIKeyHandler func(context.Context, *cmd.RegenerateAPIKey) error
var cRegisterUserHandler func(context.Context, *cmd.RegisterUser) error
var cRegisterUserProviderHandler func(context.Context, *cmd.RegisterUserProvider) error
var cRemoveSubscriberHandler func(context.Context, *cmd.RemoveSubscriber) error
var cRemoveVoteHandler func(context.Context, *cmd.RemoveVote) error
var cRenameImageFileHandler func(context.Context, *cmd.RenameImageFile) error
var cReorderReportReasonsHandler func(context.Context, *cmd.ReorderReportReasons) error
var cResolveReportHandler func(context.Context, *cmd.ResolveReport) error
var cSaveCustomOAuthConfigHandler func(context.Context, *cmd.SaveCustomOAuthConfig) error
var cSaveNavigationLinksHandler func(context.Context, *cmd.SaveNavigationLinks) error
var cSavePageDraftHandler func(context.Context, *cmd.SavePageDraft) error
var cSavePushSubscriptionHandler func(context.Context, *cmd.SavePushSubscription) error
var cSaveVerificationKeyHandler func(context.Context, *cmd.SaveVerificationKey) error
var cSetAttachmentsHandler func(context.Context, *cmd.SetAttachments) error
var cSetKeyAsVerifiedHandler func(context.Context, *cmd.SetKeyAsVerified) error
var cSetModerationPendingHandler func(context.Context, *cmd.SetModerationPending) error
var cSetPostResponseHandler func(context.Context, *cmd.SetPostResponse) error
var cSetSystemSettingsHandler func(context.Context, *cmd.SetSystemSettings) error
var cStoreBlobHandler func(context.Context, *cmd.StoreBlob) error
var cStoreEventHandler func(context.Context, *cmd.StoreEvent) error
var cSupressEmailHandler func(context.Context, *cmd.SupressEmail) error
var cTestWebhookHandler func(context.Context, *cmd.TestWebhook) error
var cToggleCommentReactionHandler func(context.Context, *cmd.ToggleCommentReaction) error
var cTogglePageReactionHandler func(context.Context, *cmd.TogglePageReaction) error
var cTogglePageSubscriptionHandler func(context.Context, *cmd.TogglePageSubscription) error
var cTriggerWebhooksHandler func(context.Context, *cmd.TriggerWebhooks) error
var cUnarchivePostHandler func(context.Context, *cmd.UnarchivePost) error
var cUnassignReportHandler func(context.Context, *cmd.UnassignReport) error
var cUnassignTagHandler func(context.Context, *cmd.UnassignTag) error
var cUnblockUserHandler func(context.Context, *cmd.UnblockUser) error
var cUnlockPostHandler func(context.Context, *cmd.UnlockPost) error
var cUpdateCannedResponseHandler func(context.Context, *cmd.UpdateCannedResponse) error
var cUpdateCommentHandler func(context.Context, *cmd.UpdateComment) error
var cUpdateContentSettingsHandler func(context.Context, *cmd.UpdateContentSettings) error
var cUpdateCurrentUserHandler func(context.Context, *cmd.UpdateCurrentUser) error
var cUpdateCurrentUserSettingsHandler func(context.Context, *cmd.UpdateCurrentUserSettings) error
var cUpdateImageFileReferencesHandler func(context.Context, *cmd.UpdateImageFileReferences) error
var cUpdateMessageBannerHandler func(context.Context, *cmd.UpdateMessageBanner) error
var cUpdatePageHandler func(context.Context, *cmd.UpdatePage) error
var cUpdatePageTagHandler func(context.Context, *cmd.UpdatePageTag) error
var cUpdatePageTopicHandler func(context.Context, *cmd.UpdatePageTopic) error
var cUpdatePostHandler func(context.Context, *cmd.UpdatePost) error
var cUpdateReportReasonHandler func(context.Context, *cmd.UpdateReportReason) error
var cUpdateTagHandler func(context.Context, *cmd.UpdateTag) error
var cUpdateTenantAdvancedSettingsHandler func(context.Context, *cmd.UpdateTenantAdvancedSettings) error
var cUpdateTenantEmailAuthAllowedSettingsHandler func(context.Context, *cmd.UpdateTenantEmailAuthAllowedSettings) error
var cUpdateTenantPrivacySettingsHandler func(context.Context, *cmd.UpdateTenantPrivacySettings) error
var cUpdateTenantSettingsHandler func(context.Context, *cmd.UpdateTenantSettings) error
var cUpdateUserHandler func(context.Context, *cmd.UpdateUser) error
var cUpdateUserAvatarHandler func(context.Context, *cmd.UpdateUserAvatar) error
var cUploadImageHandler func(context.Context, *cmd.UploadImage) error
var cUploadImageFileHandler func(context.Context, *cmd.UploadImageFile) error
var cUploadImagesHandler func(context.Context, *cmd.UploadImages) error
var cUserListCreateCompanyHandler func(context.Context, *cmd.UserListCreateCompany) error
var cUserListHandleRoleChangeHandler func(context.Context, *cmd.UserListHandleRoleChange) error
var cUserListUpdateCompanyHandler func(context.Context, *cmd.UserListUpdateCompany) error
var cUserListUpdateUserHandler func(context.Context, *cmd.UserListUpdateUser) error
var cWarnUserHandler func(context.Context, *cmd.WarnUser) error
var qCountPendingReportsHandler func(context.Context, *query.CountPendingReports) error
var qCountPostPerStatusHandler func(context.Context, *query.CountPostPerStatus) error
var qCountUnreadNotificationsHandler func(context.Context, *query.CountUnreadNotifications) error
var qCountUntaggedPostsHandler func(context.Context, *query.CountUntaggedPosts) error
var qCountUserReportsTodayHandler func(context.Context, *query.CountUserReportsToday) error
var qCountUsersHandler func(context.Context, *query.CountUsers) error
var qCountVotesSinceArchiveHandler func(context.Context, *query.CountVotesSinceArchive) error
var qCreateEditWebhookHandler func(context.Context, *query.CreateEditWebhook) error
var qDeleteWebhookHandler func(context.Context, *query.DeleteWebhook) error
var qFetchRecentSupressionsHandler func(context.Context, *query.FetchRecentSupressions) error
var qGetActiveNotificationsHandler func(context.Context, *query.GetActiveNotifications) error
var qGetActiveSubscribersHandler func(context.Context, *query.GetActiveSubscribers) error
var qGetAllPostsHandler func(context.Context, *query.GetAllPosts) error
var qGetAllPublishedPagesHandler func(context.Context, *query.GetAllPublishedPages) error
var qGetAllPushSubscriptionsHandler func(context.Context, *query.GetAllPushSubscriptions) error
var qGetAllTagsHandler func(context.Context, *query.GetAllTags) error
var qGetAllUserProvidersHandler func(context.Context, *query.GetAllUserProviders) error
var qGetAllUsersHandler func(context.Context, *query.GetAllUsers) error
var qGetAllUsersNamesHandler func(context.Context, *query.GetAllUsersNames) error
var qGetArchivablePostsHandler func(context.Context, *query.GetArchivablePosts) error
var qGetAssignedTagsHandler func(context.Context, *query.GetAssignedTags) error
var qGetAttachmentsHandler func(context.Context, *query.GetAttachments) error
var qGetBillingStateHandler func(context.Context, *query.GetBillingState) error
var qGetBillingSubscriptionHandler func(context.Context, *query.GetBillingSubscription) error
var qGetBlobByKeyHandler func(context.Context, *query.GetBlobByKey) error
var qGetCannedResponseByIDHandler func(context.Context, *query.GetCannedResponseByID) error
var qGetCommentByIDHandler func(context.Context, *query.GetCommentByID) error
var qGetCommentsByPageHandler func(context.Context, *query.GetCommentsByPage) error
var qGetCommentsByPostHandler func(context.Context, *query.GetCommentsByPost) error
var qGetCurrentUserSettingsHandler func(context.Context, *query.GetCurrentUserSettings) error
var qGetCustomOAuthConfigByProviderHandler func(context.Context, *query.GetCustomOAuthConfigByProvider) error
var qGetFirstTenantHandler func(context.Context, *query.GetFirstTenant) error
var qGetImageFileHandler func(context.Context, *query.GetImageFile) error
var qGetNameFromBlobKeyHandler func(context.Context, *query.GetNameFromBlobKey) error
var qGetNavigationLinksHandler func(context.Context, *query.GetNavigationLinks) error
var qGetNotificationByIDHandler func(context.Context, *query.GetNotificationByID) error
var qGetOAuthAuthorizationURLHandler func(context.Context, *query.GetOAuthAuthorizationURL) error
var qGetOAuthProfileHandler func(context.Context, *query.GetOAuthProfile) error
var qGetOAuthRawProfileHandler func(context.Context, *query.GetOAuthRawProfile) error
var qGetPageByIDHandler func(context.Context, *query.GetPageByID) error
var qGetPageBySlugHandler func(context.Context, *query.GetPageBySlug) error
var qGetPageDraftHandler func(context.Context, *query.GetPageDraft) error
var qGetPageSubscribersHandler func(context.Context, *query.GetPageSubscribers) error
var qGetPageTagByIDHandler func(context.Context, *query.GetPageTagByID) error
var qGetPageTagsHandler func(context.Context, *query.GetPageTags) error
var qGetPageTopicByIDHandler func(context.Context, *query.GetPageTopicByID) error
var qGetPageTopicsHandler func(context.Context, *query.GetPageTopics) error
var qGetPostByIDHandler func(context.Context, *query.GetPostByID) error
var qGetPostByNumberHandler func(context.Context, *query.GetPostByNumber) error
var qGetPostBySlugHandler func(context.Context, *query.GetPostBySlug) error
var qGetPostsByIDsHandler func(context.Context, *query.GetPostsByIDs) error
var qGetPrunableFilesHandler func(context.Context, *query.GetPrunableFiles) error
var qGetPushSubscriptionsByUserHandler func(context.Context, *query.GetPushSubscriptionsByUser) error
var qGetPushSubscriptionsByUsersHandler func(context.Context, *query.GetPushSubscriptionsByUsers) error
var qGetReportByIDHandler func(context.Context, *query.GetReportByID) error
var qGetReportReasonsHandler func(context.Context, *query.GetReportReasons) error
var qGetSystemSettingsHandler func(context.Context, *query.GetSystemSettings) error
var qGetTagBySlugHandler func(context.Context, *query.GetTagBySlug) error
var qGetTenantByDomainHandler func(context.Context, *query.GetTenantByDomain) error
var qGetTenantProfanityWordsHandler func(context.Context, *query.GetTenantProfanityWords) error
var qGetTrialingTenantContactsHandler func(context.Context, *query.GetTrialingTenantContacts) error
var qGetUserByAPIKeyHandler func(context.Context, *query.GetUserByAPIKey) error
var qGetUserByEmailHandler func(context.Context, *query.GetUserByEmail) error
var qGetUserByIDHandler func(context.Context, *query.GetUserByID) error
var qGetUserByProviderHandler func(context.Context, *query.GetUserByProvider) error
var qGetUserCommentCountHandler func(context.Context, *query.GetUserCommentCount) error
var qGetUserPostCountHandler func(context.Context, *query.GetUserPostCount) error
var qGetUserProfileStandingHandler func(context.Context, *query.GetUserProfileStanding) error
var qGetUserProfileStatsHandler func(context.Context, *query.GetUserProfileStats) error
var qGetUserReportedItemsOnPostHandler func(context.Context, *query.GetUserReportedItemsOnPost) error
var qGetUsersByIDsHandler func(context.Context, *query.GetUsersByIDs) error
var qGetUsersToNotifyHandler func(context.Context, *query.GetUsersToNotify) error
var qGetVerificationByKeyHandler func(context.Context, *query.GetVerificationByKey) error
var qGetWebhookHandler func(context.Context, *query.GetWebhook) error
var qHasPushSubscriptionHandler func(context.Context, *query.HasPushSubscription) error
var qHasUserReportedTargetHandler func(context.Context, *query.HasUserReportedTarget) error
var qIsCNAMEAvailableHandler func(context.Context, *query.IsCNAMEAvailable) error
var qIsImageFileInUseHandler func(context.Context, *query.IsImageFileInUse) error
var qIsSubdomainAvailableHandler func(context.Context, *query.IsSubdomainAvailable) error
var qListActiveOAuthProvidersHandler func(context.Context, *query.ListActiveOAuthProviders) error
var qListActiveWebhooksByTypeHandler func(context.Context, *query.ListActiveWebhooksByType) error
var qListAllOAuthProvidersHandler func(context.Context, *query.ListAllOAuthProviders) error
var qListAllReportReasonsHandler func(context.Context, *query.ListAllReportReasons) error
var qListAllWebhooksHandler func(context.Context, *query.ListAllWebhooks) error
var qListAllWebhooksByTypeHandler func(context.Context, *query.ListAllWebhooksByType) error
var qListBlobsHandler func(context.Context, *query.ListBlobs) error
var qListCannedResponsesHandler func(context.Context, *query.ListCannedResponses) error
var qListCustomOAuthConfigHandler func(context.Context, *query.ListCustomOAuthConfig) error
var qListImageFilesHandler func(context.Context, *query.ListImageFiles) error
var qListPagesHandler func(context.Context, *query.ListPages) error
var qListPostVotesHandler func(context.Context, *query.ListPostVotes) error
var qListReportsHandler func(context.Context, *query.ListReports) error
var qMarkWebhookAsFailedHandler func(context.Context, *query.MarkWebhookAsFailed) error
var qPostIsReferencedHandler func(context.Context, *query.PostIsReferenced) error
var qSearchPostsHandler func(context.Context, *query.SearchPosts) error
var qSearchUserContentHandler func(context.Context, *query.SearchUserContent) error
var qUserSubscribedToHandler func(context.Context, *query.UserSubscribedTo) error
var qUserSubscribedToPageHandler func(context.Context, *query.UserSubscribedToPage) error

var useTypedDispatch bool

func EnableTypedDispatch() { useTypedDispatch = true }
func DisableTypedDispatch() { useTypedDispatch = false }

func registerTypedHandler(handler HandlerFunc) {
	switch fn := handler.(type) {
	case func(context.Context, *cmd.ActivateBillingSubscription) error:
		cActivateBillingSubscriptionHandler = fn
	case func(context.Context, *cmd.ActivateTenant) error:
		cActivateTenantHandler = fn
	case func(context.Context, *cmd.AddNewComment) error:
		cAddNewCommentHandler = fn
	case func(context.Context, *cmd.AddNewNotification) error:
		cAddNewNotificationHandler = fn
	case func(context.Context, *cmd.AddNewPost) error:
		cAddNewPostHandler = fn
	case func(context.Context, *cmd.AddNewTag) error:
		cAddNewTagHandler = fn
	case func(context.Context, *cmd.AddPageComment) error:
		cAddPageCommentHandler = fn
	case func(context.Context, *cmd.AddSubscriber) error:
		cAddSubscriberHandler = fn
	case func(context.Context, *cmd.AddVote) error:
		cAddVoteHandler = fn
	case func(context.Context, *cmd.ArchivePost) error:
		cArchivePostHandler = fn
	case func(context.Context, *cmd.AssignReport) error:
		cAssignReportHandler = fn
	case func(context.Context, *cmd.AssignTag) error:
		cAssignTagHandler = fn
	case func(context.Context, *cmd.BlockUser) error:
		cBlockUserHandler = fn
	case func(context.Context, *cmd.BulkArchivePosts) error:
		cBulkArchivePostsHandler = fn
	case func(context.Context, *cmd.CancelBillingSubscription) error:
		cCancelBillingSubscriptionHandler = fn
	case func(context.Context, *cmd.ChangeUserEmail) error:
		cChangeUserEmailHandler = fn
	case func(context.Context, *cmd.ChangeUserRole) error:
		cChangeUserRoleHandler = fn
	case func(context.Context, *cmd.ChangeUserVisualRole) error:
		cChangeUserVisualRoleHandler = fn
	case func(context.Context, *cmd.CreateCannedResponse) error:
		cCreateCannedResponseHandler = fn
	case func(context.Context, *cmd.CreatePage) error:
		cCreatePageHandler = fn
	case func(context.Context, *cmd.CreatePageTag) error:
		cCreatePageTagHandler = fn
	case func(context.Context, *cmd.CreatePageTopic) error:
		cCreatePageTopicHandler = fn
	case func(context.Context, *cmd.CreateReport) error:
		cCreateReportHandler = fn
	case func(context.Context, *cmd.CreateReportReason) error:
		cCreateReportReasonHandler = fn
	case func(context.Context, *cmd.CreateTenant) error:
		cCreateTenantHandler = fn
	case func(context.Context, *cmd.DeleteAllPushSubscriptions) error:
		cDeleteAllPushSubscriptionsHandler = fn
	case func(context.Context, *cmd.DeleteBlob) error:
		cDeleteBlobHandler = fn
	case func(context.Context, *cmd.DeleteCannedResponse) error:
		cDeleteCannedResponseHandler = fn
	case func(context.Context, *cmd.DeleteComment) error:
		cDeleteCommentHandler = fn
	case func(context.Context, *cmd.DeleteCurrentUser) error:
		cDeleteCurrentUserHandler = fn
	case func(context.Context, *cmd.DeleteImageFile) error:
		cDeleteImageFileHandler = fn
	case func(context.Context, *cmd.DeleteImageFileReferences) error:
		cDeleteImageFileReferencesHandler = fn
	case func(context.Context, *cmd.DeleteMute) error:
		cDeleteMuteHandler = fn
	case func(context.Context, *cmd.DeletePage) error:
		cDeletePageHandler = fn
	case func(context.Context, *cmd.DeletePageTag) error:
		cDeletePageTagHandler = fn
	case func(context.Context, *cmd.DeletePageTopic) error:
		cDeletePageTopicHandler = fn
	case func(context.Context, *cmd.DeletePushSubscription) error:
		cDeletePushSubscriptionHandler = fn
	case func(context.Context, *cmd.DeletePushSubscriptionByEndpoint) error:
		cDeletePushSubscriptionByEndpointHandler = fn
	case func(context.Context, *cmd.DeleteReport) error:
		cDeleteReportHandler = fn
	case func(context.Context, *cmd.DeleteReportReason) error:
		cDeleteReportReasonHandler = fn
	case func(context.Context, *cmd.DeleteTag) error:
		cDeleteTagHandler = fn
	case func(context.Context, *cmd.DeleteWarning) error:
		cDeleteWarningHandler = fn
	case func(context.Context, *cmd.ExpireMute) error:
		cExpireMuteHandler = fn
	case func(context.Context, *cmd.ExpireWarning) error:
		cExpireWarningHandler = fn
	case func(context.Context, *cmd.GenerateCheckoutLink) error:
		cGenerateCheckoutLinkHandler = fn
	case func(context.Context, *cmd.GetWebhookProps) error:
		cGetWebhookPropsHandler = fn
	case func(context.Context, *cmd.HTTPRequest) error:
		cHTTPRequestHandler = fn
	case func(context.Context, *cmd.LockExpiredTenants) error:
		cLockExpiredTenantsHandler = fn
	case func(context.Context, *cmd.LockPost) error:
		cLockPostHandler = fn
	case func(context.Context, *cmd.MarkAllNotificationsAsRead) error:
		cMarkAllNotificationsAsReadHandler = fn
	case func(context.Context, *cmd.MarkNotificationAsRead) error:
		cMarkNotificationAsReadHandler = fn
	case func(context.Context, *cmd.MarkPostAsDuplicate) error:
		cMarkPostAsDuplicateHandler = fn
	case func(context.Context, *cmd.MuteUser) error:
		cMuteUserHandler = fn
	case func(context.Context, *cmd.ParseOAuthRawProfile) error:
		cParseOAuthRawProfileHandler = fn
	case func(context.Context, *cmd.PreviewWebhook) error:
		cPreviewWebhookHandler = fn
	case func(context.Context, *cmd.PublishScheduledPages) error:
		cPublishScheduledPagesHandler = fn
	case func(context.Context, *cmd.PurgeExpiredNotifications) error:
		cPurgeExpiredNotificationsHandler = fn
	case func(context.Context, *cmd.PurgeReadNotifications) error:
		cPurgeReadNotificationsHandler = fn
	case func(context.Context, *cmd.RefreshPageEmbeddedData) error:
		cRefreshPageEmbeddedDataHandler = fn
	case func(context.Context, *cmd.RefreshPostStats) error:
		cRefreshPostStatsHandler = fn
	case func(context.Context, *cmd.RegenerateAPIKey) error:
		cRegenerateAPIKeyHandler = fn
	case func(context.Context, *cmd.RegisterUser) error:
		cRegisterUserHandler = fn
	case func(context.Context, *cmd.RegisterUserProvider) error:
		cRegisterUserProviderHandler = fn
	case func(context.Context, *cmd.RemoveSubscriber) error:
		cRemoveSubscriberHandler = fn
	case func(context.Context, *cmd.RemoveVote) error:
		cRemoveVoteHandler = fn
	case func(context.Context, *cmd.RenameImageFile) error:
		cRenameImageFileHandler = fn
	case func(context.Context, *cmd.ReorderReportReasons) error:
		cReorderReportReasonsHandler = fn
	case func(context.Context, *cmd.ResolveReport) error:
		cResolveReportHandler = fn
	case func(context.Context, *cmd.SaveCustomOAuthConfig) error:
		cSaveCustomOAuthConfigHandler = fn
	case func(context.Context, *cmd.SaveNavigationLinks) error:
		cSaveNavigationLinksHandler = fn
	case func(context.Context, *cmd.SavePageDraft) error:
		cSavePageDraftHandler = fn
	case func(context.Context, *cmd.SavePushSubscription) error:
		cSavePushSubscriptionHandler = fn
	case func(context.Context, *cmd.SaveVerificationKey) error:
		cSaveVerificationKeyHandler = fn
	case func(context.Context, *cmd.SetAttachments) error:
		cSetAttachmentsHandler = fn
	case func(context.Context, *cmd.SetKeyAsVerified) error:
		cSetKeyAsVerifiedHandler = fn
	case func(context.Context, *cmd.SetModerationPending) error:
		cSetModerationPendingHandler = fn
	case func(context.Context, *cmd.SetPostResponse) error:
		cSetPostResponseHandler = fn
	case func(context.Context, *cmd.SetSystemSettings) error:
		cSetSystemSettingsHandler = fn
	case func(context.Context, *cmd.StoreBlob) error:
		cStoreBlobHandler = fn
	case func(context.Context, *cmd.StoreEvent) error:
		cStoreEventHandler = fn
	case func(context.Context, *cmd.SupressEmail) error:
		cSupressEmailHandler = fn
	case func(context.Context, *cmd.TestWebhook) error:
		cTestWebhookHandler = fn
	case func(context.Context, *cmd.ToggleCommentReaction) error:
		cToggleCommentReactionHandler = fn
	case func(context.Context, *cmd.TogglePageReaction) error:
		cTogglePageReactionHandler = fn
	case func(context.Context, *cmd.TogglePageSubscription) error:
		cTogglePageSubscriptionHandler = fn
	case func(context.Context, *cmd.TriggerWebhooks) error:
		cTriggerWebhooksHandler = fn
	case func(context.Context, *cmd.UnarchivePost) error:
		cUnarchivePostHandler = fn
	case func(context.Context, *cmd.UnassignReport) error:
		cUnassignReportHandler = fn
	case func(context.Context, *cmd.UnassignTag) error:
		cUnassignTagHandler = fn
	case func(context.Context, *cmd.UnblockUser) error:
		cUnblockUserHandler = fn
	case func(context.Context, *cmd.UnlockPost) error:
		cUnlockPostHandler = fn
	case func(context.Context, *cmd.UpdateCannedResponse) error:
		cUpdateCannedResponseHandler = fn
	case func(context.Context, *cmd.UpdateComment) error:
		cUpdateCommentHandler = fn
	case func(context.Context, *cmd.UpdateContentSettings) error:
		cUpdateContentSettingsHandler = fn
	case func(context.Context, *cmd.UpdateCurrentUser) error:
		cUpdateCurrentUserHandler = fn
	case func(context.Context, *cmd.UpdateCurrentUserSettings) error:
		cUpdateCurrentUserSettingsHandler = fn
	case func(context.Context, *cmd.UpdateImageFileReferences) error:
		cUpdateImageFileReferencesHandler = fn
	case func(context.Context, *cmd.UpdateMessageBanner) error:
		cUpdateMessageBannerHandler = fn
	case func(context.Context, *cmd.UpdatePage) error:
		cUpdatePageHandler = fn
	case func(context.Context, *cmd.UpdatePageTag) error:
		cUpdatePageTagHandler = fn
	case func(context.Context, *cmd.UpdatePageTopic) error:
		cUpdatePageTopicHandler = fn
	case func(context.Context, *cmd.UpdatePost) error:
		cUpdatePostHandler = fn
	case func(context.Context, *cmd.UpdateReportReason) error:
		cUpdateReportReasonHandler = fn
	case func(context.Context, *cmd.UpdateTag) error:
		cUpdateTagHandler = fn
	case func(context.Context, *cmd.UpdateTenantAdvancedSettings) error:
		cUpdateTenantAdvancedSettingsHandler = fn
	case func(context.Context, *cmd.UpdateTenantEmailAuthAllowedSettings) error:
		cUpdateTenantEmailAuthAllowedSettingsHandler = fn
	case func(context.Context, *cmd.UpdateTenantPrivacySettings) error:
		cUpdateTenantPrivacySettingsHandler = fn
	case func(context.Context, *cmd.UpdateTenantSettings) error:
		cUpdateTenantSettingsHandler = fn
	case func(context.Context, *cmd.UpdateUser) error:
		cUpdateUserHandler = fn
	case func(context.Context, *cmd.UpdateUserAvatar) error:
		cUpdateUserAvatarHandler = fn
	case func(context.Context, *cmd.UploadImage) error:
		cUploadImageHandler = fn
	case func(context.Context, *cmd.UploadImageFile) error:
		cUploadImageFileHandler = fn
	case func(context.Context, *cmd.UploadImages) error:
		cUploadImagesHandler = fn
	case func(context.Context, *cmd.UserListCreateCompany) error:
		cUserListCreateCompanyHandler = fn
	case func(context.Context, *cmd.UserListHandleRoleChange) error:
		cUserListHandleRoleChangeHandler = fn
	case func(context.Context, *cmd.UserListUpdateCompany) error:
		cUserListUpdateCompanyHandler = fn
	case func(context.Context, *cmd.UserListUpdateUser) error:
		cUserListUpdateUserHandler = fn
	case func(context.Context, *cmd.WarnUser) error:
		cWarnUserHandler = fn
	case func(context.Context, *query.CountPendingReports) error:
		qCountPendingReportsHandler = fn
	case func(context.Context, *query.CountPostPerStatus) error:
		qCountPostPerStatusHandler = fn
	case func(context.Context, *query.CountUnreadNotifications) error:
		qCountUnreadNotificationsHandler = fn
	case func(context.Context, *query.CountUntaggedPosts) error:
		qCountUntaggedPostsHandler = fn
	case func(context.Context, *query.CountUserReportsToday) error:
		qCountUserReportsTodayHandler = fn
	case func(context.Context, *query.CountUsers) error:
		qCountUsersHandler = fn
	case func(context.Context, *query.CountVotesSinceArchive) error:
		qCountVotesSinceArchiveHandler = fn
	case func(context.Context, *query.CreateEditWebhook) error:
		qCreateEditWebhookHandler = fn
	case func(context.Context, *query.DeleteWebhook) error:
		qDeleteWebhookHandler = fn
	case func(context.Context, *query.FetchRecentSupressions) error:
		qFetchRecentSupressionsHandler = fn
	case func(context.Context, *query.GetActiveNotifications) error:
		qGetActiveNotificationsHandler = fn
	case func(context.Context, *query.GetActiveSubscribers) error:
		qGetActiveSubscribersHandler = fn
	case func(context.Context, *query.GetAllPosts) error:
		qGetAllPostsHandler = fn
	case func(context.Context, *query.GetAllPublishedPages) error:
		qGetAllPublishedPagesHandler = fn
	case func(context.Context, *query.GetAllPushSubscriptions) error:
		qGetAllPushSubscriptionsHandler = fn
	case func(context.Context, *query.GetAllTags) error:
		qGetAllTagsHandler = fn
	case func(context.Context, *query.GetAllUserProviders) error:
		qGetAllUserProvidersHandler = fn
	case func(context.Context, *query.GetAllUsers) error:
		qGetAllUsersHandler = fn
	case func(context.Context, *query.GetAllUsersNames) error:
		qGetAllUsersNamesHandler = fn
	case func(context.Context, *query.GetArchivablePosts) error:
		qGetArchivablePostsHandler = fn
	case func(context.Context, *query.GetAssignedTags) error:
		qGetAssignedTagsHandler = fn
	case func(context.Context, *query.GetAttachments) error:
		qGetAttachmentsHandler = fn
	case func(context.Context, *query.GetBillingState) error:
		qGetBillingStateHandler = fn
	case func(context.Context, *query.GetBillingSubscription) error:
		qGetBillingSubscriptionHandler = fn
	case func(context.Context, *query.GetBlobByKey) error:
		qGetBlobByKeyHandler = fn
	case func(context.Context, *query.GetCannedResponseByID) error:
		qGetCannedResponseByIDHandler = fn
	case func(context.Context, *query.GetCommentByID) error:
		qGetCommentByIDHandler = fn
	case func(context.Context, *query.GetCommentsByPage) error:
		qGetCommentsByPageHandler = fn
	case func(context.Context, *query.GetCommentsByPost) error:
		qGetCommentsByPostHandler = fn
	case func(context.Context, *query.GetCurrentUserSettings) error:
		qGetCurrentUserSettingsHandler = fn
	case func(context.Context, *query.GetCustomOAuthConfigByProvider) error:
		qGetCustomOAuthConfigByProviderHandler = fn
	case func(context.Context, *query.GetFirstTenant) error:
		qGetFirstTenantHandler = fn
	case func(context.Context, *query.GetImageFile) error:
		qGetImageFileHandler = fn
	case func(context.Context, *query.GetNameFromBlobKey) error:
		qGetNameFromBlobKeyHandler = fn
	case func(context.Context, *query.GetNavigationLinks) error:
		qGetNavigationLinksHandler = fn
	case func(context.Context, *query.GetNotificationByID) error:
		qGetNotificationByIDHandler = fn
	case func(context.Context, *query.GetOAuthAuthorizationURL) error:
		qGetOAuthAuthorizationURLHandler = fn
	case func(context.Context, *query.GetOAuthProfile) error:
		qGetOAuthProfileHandler = fn
	case func(context.Context, *query.GetOAuthRawProfile) error:
		qGetOAuthRawProfileHandler = fn
	case func(context.Context, *query.GetPageByID) error:
		qGetPageByIDHandler = fn
	case func(context.Context, *query.GetPageBySlug) error:
		qGetPageBySlugHandler = fn
	case func(context.Context, *query.GetPageDraft) error:
		qGetPageDraftHandler = fn
	case func(context.Context, *query.GetPageSubscribers) error:
		qGetPageSubscribersHandler = fn
	case func(context.Context, *query.GetPageTagByID) error:
		qGetPageTagByIDHandler = fn
	case func(context.Context, *query.GetPageTags) error:
		qGetPageTagsHandler = fn
	case func(context.Context, *query.GetPageTopicByID) error:
		qGetPageTopicByIDHandler = fn
	case func(context.Context, *query.GetPageTopics) error:
		qGetPageTopicsHandler = fn
	case func(context.Context, *query.GetPostByID) error:
		qGetPostByIDHandler = fn
	case func(context.Context, *query.GetPostByNumber) error:
		qGetPostByNumberHandler = fn
	case func(context.Context, *query.GetPostBySlug) error:
		qGetPostBySlugHandler = fn
	case func(context.Context, *query.GetPostsByIDs) error:
		qGetPostsByIDsHandler = fn
	case func(context.Context, *query.GetPrunableFiles) error:
		qGetPrunableFilesHandler = fn
	case func(context.Context, *query.GetPushSubscriptionsByUser) error:
		qGetPushSubscriptionsByUserHandler = fn
	case func(context.Context, *query.GetPushSubscriptionsByUsers) error:
		qGetPushSubscriptionsByUsersHandler = fn
	case func(context.Context, *query.GetReportByID) error:
		qGetReportByIDHandler = fn
	case func(context.Context, *query.GetReportReasons) error:
		qGetReportReasonsHandler = fn
	case func(context.Context, *query.GetSystemSettings) error:
		qGetSystemSettingsHandler = fn
	case func(context.Context, *query.GetTagBySlug) error:
		qGetTagBySlugHandler = fn
	case func(context.Context, *query.GetTenantByDomain) error:
		qGetTenantByDomainHandler = fn
	case func(context.Context, *query.GetTenantProfanityWords) error:
		qGetTenantProfanityWordsHandler = fn
	case func(context.Context, *query.GetTrialingTenantContacts) error:
		qGetTrialingTenantContactsHandler = fn
	case func(context.Context, *query.GetUserByAPIKey) error:
		qGetUserByAPIKeyHandler = fn
	case func(context.Context, *query.GetUserByEmail) error:
		qGetUserByEmailHandler = fn
	case func(context.Context, *query.GetUserByID) error:
		qGetUserByIDHandler = fn
	case func(context.Context, *query.GetUserByProvider) error:
		qGetUserByProviderHandler = fn
	case func(context.Context, *query.GetUserCommentCount) error:
		qGetUserCommentCountHandler = fn
	case func(context.Context, *query.GetUserPostCount) error:
		qGetUserPostCountHandler = fn
	case func(context.Context, *query.GetUserProfileStanding) error:
		qGetUserProfileStandingHandler = fn
	case func(context.Context, *query.GetUserProfileStats) error:
		qGetUserProfileStatsHandler = fn
	case func(context.Context, *query.GetUserReportedItemsOnPost) error:
		qGetUserReportedItemsOnPostHandler = fn
	case func(context.Context, *query.GetUsersByIDs) error:
		qGetUsersByIDsHandler = fn
	case func(context.Context, *query.GetUsersToNotify) error:
		qGetUsersToNotifyHandler = fn
	case func(context.Context, *query.GetVerificationByKey) error:
		qGetVerificationByKeyHandler = fn
	case func(context.Context, *query.GetWebhook) error:
		qGetWebhookHandler = fn
	case func(context.Context, *query.HasPushSubscription) error:
		qHasPushSubscriptionHandler = fn
	case func(context.Context, *query.HasUserReportedTarget) error:
		qHasUserReportedTargetHandler = fn
	case func(context.Context, *query.IsCNAMEAvailable) error:
		qIsCNAMEAvailableHandler = fn
	case func(context.Context, *query.IsImageFileInUse) error:
		qIsImageFileInUseHandler = fn
	case func(context.Context, *query.IsSubdomainAvailable) error:
		qIsSubdomainAvailableHandler = fn
	case func(context.Context, *query.ListActiveOAuthProviders) error:
		qListActiveOAuthProvidersHandler = fn
	case func(context.Context, *query.ListActiveWebhooksByType) error:
		qListActiveWebhooksByTypeHandler = fn
	case func(context.Context, *query.ListAllOAuthProviders) error:
		qListAllOAuthProvidersHandler = fn
	case func(context.Context, *query.ListAllReportReasons) error:
		qListAllReportReasonsHandler = fn
	case func(context.Context, *query.ListAllWebhooks) error:
		qListAllWebhooksHandler = fn
	case func(context.Context, *query.ListAllWebhooksByType) error:
		qListAllWebhooksByTypeHandler = fn
	case func(context.Context, *query.ListBlobs) error:
		qListBlobsHandler = fn
	case func(context.Context, *query.ListCannedResponses) error:
		qListCannedResponsesHandler = fn
	case func(context.Context, *query.ListCustomOAuthConfig) error:
		qListCustomOAuthConfigHandler = fn
	case func(context.Context, *query.ListImageFiles) error:
		qListImageFilesHandler = fn
	case func(context.Context, *query.ListPages) error:
		qListPagesHandler = fn
	case func(context.Context, *query.ListPostVotes) error:
		qListPostVotesHandler = fn
	case func(context.Context, *query.ListReports) error:
		qListReportsHandler = fn
	case func(context.Context, *query.MarkWebhookAsFailed) error:
		qMarkWebhookAsFailedHandler = fn
	case func(context.Context, *query.PostIsReferenced) error:
		qPostIsReferencedHandler = fn
	case func(context.Context, *query.SearchPosts) error:
		qSearchPostsHandler = fn
	case func(context.Context, *query.SearchUserContent) error:
		qSearchUserContentHandler = fn
	case func(context.Context, *query.UserSubscribedTo) error:
		qUserSubscribedToHandler = fn
	case func(context.Context, *query.UserSubscribedToPage) error:
		qUserSubscribedToPageHandler = fn
	}
}

func dispatchTyped(ctx context.Context, msg Msg) error {
	switch m := msg.(type) {
	case *cmd.ActivateBillingSubscription:
		if cActivateBillingSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ActivateBillingSubscription")
		}
		return cActivateBillingSubscriptionHandler(ctx, m)
	case *cmd.ActivateTenant:
		if cActivateTenantHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ActivateTenant")
		}
		return cActivateTenantHandler(ctx, m)
	case *cmd.AddNewComment:
		if cAddNewCommentHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddNewComment")
		}
		return cAddNewCommentHandler(ctx, m)
	case *cmd.AddNewNotification:
		if cAddNewNotificationHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddNewNotification")
		}
		return cAddNewNotificationHandler(ctx, m)
	case *cmd.AddNewPost:
		if cAddNewPostHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddNewPost")
		}
		return cAddNewPostHandler(ctx, m)
	case *cmd.AddNewTag:
		if cAddNewTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddNewTag")
		}
		return cAddNewTagHandler(ctx, m)
	case *cmd.AddPageComment:
		if cAddPageCommentHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddPageComment")
		}
		return cAddPageCommentHandler(ctx, m)
	case *cmd.AddSubscriber:
		if cAddSubscriberHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddSubscriber")
		}
		return cAddSubscriberHandler(ctx, m)
	case *cmd.AddVote:
		if cAddVoteHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AddVote")
		}
		return cAddVoteHandler(ctx, m)
	case *cmd.ArchivePost:
		if cArchivePostHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ArchivePost")
		}
		return cArchivePostHandler(ctx, m)
	case *cmd.AssignReport:
		if cAssignReportHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AssignReport")
		}
		return cAssignReportHandler(ctx, m)
	case *cmd.AssignTag:
		if cAssignTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.AssignTag")
		}
		return cAssignTagHandler(ctx, m)
	case *cmd.BlockUser:
		if cBlockUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.BlockUser")
		}
		return cBlockUserHandler(ctx, m)
	case *cmd.BulkArchivePosts:
		if cBulkArchivePostsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.BulkArchivePosts")
		}
		return cBulkArchivePostsHandler(ctx, m)
	case *cmd.CancelBillingSubscription:
		if cCancelBillingSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CancelBillingSubscription")
		}
		return cCancelBillingSubscriptionHandler(ctx, m)
	case *cmd.ChangeUserEmail:
		if cChangeUserEmailHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ChangeUserEmail")
		}
		return cChangeUserEmailHandler(ctx, m)
	case *cmd.ChangeUserRole:
		if cChangeUserRoleHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ChangeUserRole")
		}
		return cChangeUserRoleHandler(ctx, m)
	case *cmd.ChangeUserVisualRole:
		if cChangeUserVisualRoleHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ChangeUserVisualRole")
		}
		return cChangeUserVisualRoleHandler(ctx, m)
	case *cmd.CreateCannedResponse:
		if cCreateCannedResponseHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreateCannedResponse")
		}
		return cCreateCannedResponseHandler(ctx, m)
	case *cmd.CreatePage:
		if cCreatePageHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreatePage")
		}
		return cCreatePageHandler(ctx, m)
	case *cmd.CreatePageTag:
		if cCreatePageTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreatePageTag")
		}
		return cCreatePageTagHandler(ctx, m)
	case *cmd.CreatePageTopic:
		if cCreatePageTopicHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreatePageTopic")
		}
		return cCreatePageTopicHandler(ctx, m)
	case *cmd.CreateReport:
		if cCreateReportHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreateReport")
		}
		return cCreateReportHandler(ctx, m)
	case *cmd.CreateReportReason:
		if cCreateReportReasonHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreateReportReason")
		}
		return cCreateReportReasonHandler(ctx, m)
	case *cmd.CreateTenant:
		if cCreateTenantHandler == nil {
			return fmt.Errorf("handler not registered: cmd.CreateTenant")
		}
		return cCreateTenantHandler(ctx, m)
	case *cmd.DeleteAllPushSubscriptions:
		if cDeleteAllPushSubscriptionsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteAllPushSubscriptions")
		}
		return cDeleteAllPushSubscriptionsHandler(ctx, m)
	case *cmd.DeleteBlob:
		if cDeleteBlobHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteBlob")
		}
		return cDeleteBlobHandler(ctx, m)
	case *cmd.DeleteCannedResponse:
		if cDeleteCannedResponseHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteCannedResponse")
		}
		return cDeleteCannedResponseHandler(ctx, m)
	case *cmd.DeleteComment:
		if cDeleteCommentHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteComment")
		}
		return cDeleteCommentHandler(ctx, m)
	case *cmd.DeleteCurrentUser:
		if cDeleteCurrentUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteCurrentUser")
		}
		return cDeleteCurrentUserHandler(ctx, m)
	case *cmd.DeleteImageFile:
		if cDeleteImageFileHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteImageFile")
		}
		return cDeleteImageFileHandler(ctx, m)
	case *cmd.DeleteImageFileReferences:
		if cDeleteImageFileReferencesHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteImageFileReferences")
		}
		return cDeleteImageFileReferencesHandler(ctx, m)
	case *cmd.DeleteMute:
		if cDeleteMuteHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteMute")
		}
		return cDeleteMuteHandler(ctx, m)
	case *cmd.DeletePage:
		if cDeletePageHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeletePage")
		}
		return cDeletePageHandler(ctx, m)
	case *cmd.DeletePageTag:
		if cDeletePageTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeletePageTag")
		}
		return cDeletePageTagHandler(ctx, m)
	case *cmd.DeletePageTopic:
		if cDeletePageTopicHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeletePageTopic")
		}
		return cDeletePageTopicHandler(ctx, m)
	case *cmd.DeletePushSubscription:
		if cDeletePushSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeletePushSubscription")
		}
		return cDeletePushSubscriptionHandler(ctx, m)
	case *cmd.DeletePushSubscriptionByEndpoint:
		if cDeletePushSubscriptionByEndpointHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeletePushSubscriptionByEndpoint")
		}
		return cDeletePushSubscriptionByEndpointHandler(ctx, m)
	case *cmd.DeleteReport:
		if cDeleteReportHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteReport")
		}
		return cDeleteReportHandler(ctx, m)
	case *cmd.DeleteReportReason:
		if cDeleteReportReasonHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteReportReason")
		}
		return cDeleteReportReasonHandler(ctx, m)
	case *cmd.DeleteTag:
		if cDeleteTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteTag")
		}
		return cDeleteTagHandler(ctx, m)
	case *cmd.DeleteWarning:
		if cDeleteWarningHandler == nil {
			return fmt.Errorf("handler not registered: cmd.DeleteWarning")
		}
		return cDeleteWarningHandler(ctx, m)
	case *cmd.ExpireMute:
		if cExpireMuteHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ExpireMute")
		}
		return cExpireMuteHandler(ctx, m)
	case *cmd.ExpireWarning:
		if cExpireWarningHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ExpireWarning")
		}
		return cExpireWarningHandler(ctx, m)
	case *cmd.GenerateCheckoutLink:
		if cGenerateCheckoutLinkHandler == nil {
			return fmt.Errorf("handler not registered: cmd.GenerateCheckoutLink")
		}
		return cGenerateCheckoutLinkHandler(ctx, m)
	case *cmd.GetWebhookProps:
		if cGetWebhookPropsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.GetWebhookProps")
		}
		return cGetWebhookPropsHandler(ctx, m)
	case *cmd.HTTPRequest:
		if cHTTPRequestHandler == nil {
			return fmt.Errorf("handler not registered: cmd.HTTPRequest")
		}
		return cHTTPRequestHandler(ctx, m)
	case *cmd.LockExpiredTenants:
		if cLockExpiredTenantsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.LockExpiredTenants")
		}
		return cLockExpiredTenantsHandler(ctx, m)
	case *cmd.LockPost:
		if cLockPostHandler == nil {
			return fmt.Errorf("handler not registered: cmd.LockPost")
		}
		return cLockPostHandler(ctx, m)
	case *cmd.MarkAllNotificationsAsRead:
		if cMarkAllNotificationsAsReadHandler == nil {
			return fmt.Errorf("handler not registered: cmd.MarkAllNotificationsAsRead")
		}
		return cMarkAllNotificationsAsReadHandler(ctx, m)
	case *cmd.MarkNotificationAsRead:
		if cMarkNotificationAsReadHandler == nil {
			return fmt.Errorf("handler not registered: cmd.MarkNotificationAsRead")
		}
		return cMarkNotificationAsReadHandler(ctx, m)
	case *cmd.MarkPostAsDuplicate:
		if cMarkPostAsDuplicateHandler == nil {
			return fmt.Errorf("handler not registered: cmd.MarkPostAsDuplicate")
		}
		return cMarkPostAsDuplicateHandler(ctx, m)
	case *cmd.MuteUser:
		if cMuteUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.MuteUser")
		}
		return cMuteUserHandler(ctx, m)
	case *cmd.ParseOAuthRawProfile:
		if cParseOAuthRawProfileHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ParseOAuthRawProfile")
		}
		return cParseOAuthRawProfileHandler(ctx, m)
	case *cmd.PreviewWebhook:
		if cPreviewWebhookHandler == nil {
			return fmt.Errorf("handler not registered: cmd.PreviewWebhook")
		}
		return cPreviewWebhookHandler(ctx, m)
	case *cmd.PublishScheduledPages:
		if cPublishScheduledPagesHandler == nil {
			return fmt.Errorf("handler not registered: cmd.PublishScheduledPages")
		}
		return cPublishScheduledPagesHandler(ctx, m)
	case *cmd.PurgeExpiredNotifications:
		if cPurgeExpiredNotificationsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.PurgeExpiredNotifications")
		}
		return cPurgeExpiredNotificationsHandler(ctx, m)
	case *cmd.PurgeReadNotifications:
		if cPurgeReadNotificationsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.PurgeReadNotifications")
		}
		return cPurgeReadNotificationsHandler(ctx, m)
	case *cmd.RefreshPageEmbeddedData:
		if cRefreshPageEmbeddedDataHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RefreshPageEmbeddedData")
		}
		return cRefreshPageEmbeddedDataHandler(ctx, m)
	case *cmd.RefreshPostStats:
		if cRefreshPostStatsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RefreshPostStats")
		}
		return cRefreshPostStatsHandler(ctx, m)
	case *cmd.RegenerateAPIKey:
		if cRegenerateAPIKeyHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RegenerateAPIKey")
		}
		return cRegenerateAPIKeyHandler(ctx, m)
	case *cmd.RegisterUser:
		if cRegisterUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RegisterUser")
		}
		return cRegisterUserHandler(ctx, m)
	case *cmd.RegisterUserProvider:
		if cRegisterUserProviderHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RegisterUserProvider")
		}
		return cRegisterUserProviderHandler(ctx, m)
	case *cmd.RemoveSubscriber:
		if cRemoveSubscriberHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RemoveSubscriber")
		}
		return cRemoveSubscriberHandler(ctx, m)
	case *cmd.RemoveVote:
		if cRemoveVoteHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RemoveVote")
		}
		return cRemoveVoteHandler(ctx, m)
	case *cmd.RenameImageFile:
		if cRenameImageFileHandler == nil {
			return fmt.Errorf("handler not registered: cmd.RenameImageFile")
		}
		return cRenameImageFileHandler(ctx, m)
	case *cmd.ReorderReportReasons:
		if cReorderReportReasonsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ReorderReportReasons")
		}
		return cReorderReportReasonsHandler(ctx, m)
	case *cmd.ResolveReport:
		if cResolveReportHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ResolveReport")
		}
		return cResolveReportHandler(ctx, m)
	case *cmd.SaveCustomOAuthConfig:
		if cSaveCustomOAuthConfigHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SaveCustomOAuthConfig")
		}
		return cSaveCustomOAuthConfigHandler(ctx, m)
	case *cmd.SaveNavigationLinks:
		if cSaveNavigationLinksHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SaveNavigationLinks")
		}
		return cSaveNavigationLinksHandler(ctx, m)
	case *cmd.SavePageDraft:
		if cSavePageDraftHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SavePageDraft")
		}
		return cSavePageDraftHandler(ctx, m)
	case *cmd.SavePushSubscription:
		if cSavePushSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SavePushSubscription")
		}
		return cSavePushSubscriptionHandler(ctx, m)
	case *cmd.SaveVerificationKey:
		if cSaveVerificationKeyHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SaveVerificationKey")
		}
		return cSaveVerificationKeyHandler(ctx, m)
	case *cmd.SetAttachments:
		if cSetAttachmentsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SetAttachments")
		}
		return cSetAttachmentsHandler(ctx, m)
	case *cmd.SetKeyAsVerified:
		if cSetKeyAsVerifiedHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SetKeyAsVerified")
		}
		return cSetKeyAsVerifiedHandler(ctx, m)
	case *cmd.SetModerationPending:
		if cSetModerationPendingHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SetModerationPending")
		}
		return cSetModerationPendingHandler(ctx, m)
	case *cmd.SetPostResponse:
		if cSetPostResponseHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SetPostResponse")
		}
		return cSetPostResponseHandler(ctx, m)
	case *cmd.SetSystemSettings:
		if cSetSystemSettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SetSystemSettings")
		}
		return cSetSystemSettingsHandler(ctx, m)
	case *cmd.StoreBlob:
		if cStoreBlobHandler == nil {
			return fmt.Errorf("handler not registered: cmd.StoreBlob")
		}
		return cStoreBlobHandler(ctx, m)
	case *cmd.StoreEvent:
		if cStoreEventHandler == nil {
			return fmt.Errorf("handler not registered: cmd.StoreEvent")
		}
		return cStoreEventHandler(ctx, m)
	case *cmd.SupressEmail:
		if cSupressEmailHandler == nil {
			return fmt.Errorf("handler not registered: cmd.SupressEmail")
		}
		return cSupressEmailHandler(ctx, m)
	case *cmd.TestWebhook:
		if cTestWebhookHandler == nil {
			return fmt.Errorf("handler not registered: cmd.TestWebhook")
		}
		return cTestWebhookHandler(ctx, m)
	case *cmd.ToggleCommentReaction:
		if cToggleCommentReactionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.ToggleCommentReaction")
		}
		return cToggleCommentReactionHandler(ctx, m)
	case *cmd.TogglePageReaction:
		if cTogglePageReactionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.TogglePageReaction")
		}
		return cTogglePageReactionHandler(ctx, m)
	case *cmd.TogglePageSubscription:
		if cTogglePageSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: cmd.TogglePageSubscription")
		}
		return cTogglePageSubscriptionHandler(ctx, m)
	case *cmd.TriggerWebhooks:
		if cTriggerWebhooksHandler == nil {
			return fmt.Errorf("handler not registered: cmd.TriggerWebhooks")
		}
		return cTriggerWebhooksHandler(ctx, m)
	case *cmd.UnarchivePost:
		if cUnarchivePostHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UnarchivePost")
		}
		return cUnarchivePostHandler(ctx, m)
	case *cmd.UnassignReport:
		if cUnassignReportHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UnassignReport")
		}
		return cUnassignReportHandler(ctx, m)
	case *cmd.UnassignTag:
		if cUnassignTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UnassignTag")
		}
		return cUnassignTagHandler(ctx, m)
	case *cmd.UnblockUser:
		if cUnblockUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UnblockUser")
		}
		return cUnblockUserHandler(ctx, m)
	case *cmd.UnlockPost:
		if cUnlockPostHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UnlockPost")
		}
		return cUnlockPostHandler(ctx, m)
	case *cmd.UpdateCannedResponse:
		if cUpdateCannedResponseHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateCannedResponse")
		}
		return cUpdateCannedResponseHandler(ctx, m)
	case *cmd.UpdateComment:
		if cUpdateCommentHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateComment")
		}
		return cUpdateCommentHandler(ctx, m)
	case *cmd.UpdateContentSettings:
		if cUpdateContentSettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateContentSettings")
		}
		return cUpdateContentSettingsHandler(ctx, m)
	case *cmd.UpdateCurrentUser:
		if cUpdateCurrentUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateCurrentUser")
		}
		return cUpdateCurrentUserHandler(ctx, m)
	case *cmd.UpdateCurrentUserSettings:
		if cUpdateCurrentUserSettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateCurrentUserSettings")
		}
		return cUpdateCurrentUserSettingsHandler(ctx, m)
	case *cmd.UpdateImageFileReferences:
		if cUpdateImageFileReferencesHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateImageFileReferences")
		}
		return cUpdateImageFileReferencesHandler(ctx, m)
	case *cmd.UpdateMessageBanner:
		if cUpdateMessageBannerHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateMessageBanner")
		}
		return cUpdateMessageBannerHandler(ctx, m)
	case *cmd.UpdatePage:
		if cUpdatePageHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdatePage")
		}
		return cUpdatePageHandler(ctx, m)
	case *cmd.UpdatePageTag:
		if cUpdatePageTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdatePageTag")
		}
		return cUpdatePageTagHandler(ctx, m)
	case *cmd.UpdatePageTopic:
		if cUpdatePageTopicHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdatePageTopic")
		}
		return cUpdatePageTopicHandler(ctx, m)
	case *cmd.UpdatePost:
		if cUpdatePostHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdatePost")
		}
		return cUpdatePostHandler(ctx, m)
	case *cmd.UpdateReportReason:
		if cUpdateReportReasonHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateReportReason")
		}
		return cUpdateReportReasonHandler(ctx, m)
	case *cmd.UpdateTag:
		if cUpdateTagHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateTag")
		}
		return cUpdateTagHandler(ctx, m)
	case *cmd.UpdateTenantAdvancedSettings:
		if cUpdateTenantAdvancedSettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateTenantAdvancedSettings")
		}
		return cUpdateTenantAdvancedSettingsHandler(ctx, m)
	case *cmd.UpdateTenantEmailAuthAllowedSettings:
		if cUpdateTenantEmailAuthAllowedSettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateTenantEmailAuthAllowedSettings")
		}
		return cUpdateTenantEmailAuthAllowedSettingsHandler(ctx, m)
	case *cmd.UpdateTenantPrivacySettings:
		if cUpdateTenantPrivacySettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateTenantPrivacySettings")
		}
		return cUpdateTenantPrivacySettingsHandler(ctx, m)
	case *cmd.UpdateTenantSettings:
		if cUpdateTenantSettingsHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateTenantSettings")
		}
		return cUpdateTenantSettingsHandler(ctx, m)
	case *cmd.UpdateUser:
		if cUpdateUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateUser")
		}
		return cUpdateUserHandler(ctx, m)
	case *cmd.UpdateUserAvatar:
		if cUpdateUserAvatarHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UpdateUserAvatar")
		}
		return cUpdateUserAvatarHandler(ctx, m)
	case *cmd.UploadImage:
		if cUploadImageHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UploadImage")
		}
		return cUploadImageHandler(ctx, m)
	case *cmd.UploadImageFile:
		if cUploadImageFileHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UploadImageFile")
		}
		return cUploadImageFileHandler(ctx, m)
	case *cmd.UploadImages:
		if cUploadImagesHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UploadImages")
		}
		return cUploadImagesHandler(ctx, m)
	case *cmd.UserListCreateCompany:
		if cUserListCreateCompanyHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UserListCreateCompany")
		}
		return cUserListCreateCompanyHandler(ctx, m)
	case *cmd.UserListHandleRoleChange:
		if cUserListHandleRoleChangeHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UserListHandleRoleChange")
		}
		return cUserListHandleRoleChangeHandler(ctx, m)
	case *cmd.UserListUpdateCompany:
		if cUserListUpdateCompanyHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UserListUpdateCompany")
		}
		return cUserListUpdateCompanyHandler(ctx, m)
	case *cmd.UserListUpdateUser:
		if cUserListUpdateUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.UserListUpdateUser")
		}
		return cUserListUpdateUserHandler(ctx, m)
	case *cmd.WarnUser:
		if cWarnUserHandler == nil {
			return fmt.Errorf("handler not registered: cmd.WarnUser")
		}
		return cWarnUserHandler(ctx, m)
	case *query.CountPendingReports:
		if qCountPendingReportsHandler == nil {
			return fmt.Errorf("handler not registered: query.CountPendingReports")
		}
		return qCountPendingReportsHandler(ctx, m)
	case *query.CountPostPerStatus:
		if qCountPostPerStatusHandler == nil {
			return fmt.Errorf("handler not registered: query.CountPostPerStatus")
		}
		return qCountPostPerStatusHandler(ctx, m)
	case *query.CountUnreadNotifications:
		if qCountUnreadNotificationsHandler == nil {
			return fmt.Errorf("handler not registered: query.CountUnreadNotifications")
		}
		return qCountUnreadNotificationsHandler(ctx, m)
	case *query.CountUntaggedPosts:
		if qCountUntaggedPostsHandler == nil {
			return fmt.Errorf("handler not registered: query.CountUntaggedPosts")
		}
		return qCountUntaggedPostsHandler(ctx, m)
	case *query.CountUserReportsToday:
		if qCountUserReportsTodayHandler == nil {
			return fmt.Errorf("handler not registered: query.CountUserReportsToday")
		}
		return qCountUserReportsTodayHandler(ctx, m)
	case *query.CountUsers:
		if qCountUsersHandler == nil {
			return fmt.Errorf("handler not registered: query.CountUsers")
		}
		return qCountUsersHandler(ctx, m)
	case *query.CountVotesSinceArchive:
		if qCountVotesSinceArchiveHandler == nil {
			return fmt.Errorf("handler not registered: query.CountVotesSinceArchive")
		}
		return qCountVotesSinceArchiveHandler(ctx, m)
	case *query.CreateEditWebhook:
		if qCreateEditWebhookHandler == nil {
			return fmt.Errorf("handler not registered: query.CreateEditWebhook")
		}
		return qCreateEditWebhookHandler(ctx, m)
	case *query.DeleteWebhook:
		if qDeleteWebhookHandler == nil {
			return fmt.Errorf("handler not registered: query.DeleteWebhook")
		}
		return qDeleteWebhookHandler(ctx, m)
	case *query.FetchRecentSupressions:
		if qFetchRecentSupressionsHandler == nil {
			return fmt.Errorf("handler not registered: query.FetchRecentSupressions")
		}
		return qFetchRecentSupressionsHandler(ctx, m)
	case *query.GetActiveNotifications:
		if qGetActiveNotificationsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetActiveNotifications")
		}
		return qGetActiveNotificationsHandler(ctx, m)
	case *query.GetActiveSubscribers:
		if qGetActiveSubscribersHandler == nil {
			return fmt.Errorf("handler not registered: query.GetActiveSubscribers")
		}
		return qGetActiveSubscribersHandler(ctx, m)
	case *query.GetAllPosts:
		if qGetAllPostsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllPosts")
		}
		return qGetAllPostsHandler(ctx, m)
	case *query.GetAllPublishedPages:
		if qGetAllPublishedPagesHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllPublishedPages")
		}
		return qGetAllPublishedPagesHandler(ctx, m)
	case *query.GetAllPushSubscriptions:
		if qGetAllPushSubscriptionsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllPushSubscriptions")
		}
		return qGetAllPushSubscriptionsHandler(ctx, m)
	case *query.GetAllTags:
		if qGetAllTagsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllTags")
		}
		return qGetAllTagsHandler(ctx, m)
	case *query.GetAllUserProviders:
		if qGetAllUserProvidersHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllUserProviders")
		}
		return qGetAllUserProvidersHandler(ctx, m)
	case *query.GetAllUsers:
		if qGetAllUsersHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllUsers")
		}
		return qGetAllUsersHandler(ctx, m)
	case *query.GetAllUsersNames:
		if qGetAllUsersNamesHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAllUsersNames")
		}
		return qGetAllUsersNamesHandler(ctx, m)
	case *query.GetArchivablePosts:
		if qGetArchivablePostsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetArchivablePosts")
		}
		return qGetArchivablePostsHandler(ctx, m)
	case *query.GetAssignedTags:
		if qGetAssignedTagsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAssignedTags")
		}
		return qGetAssignedTagsHandler(ctx, m)
	case *query.GetAttachments:
		if qGetAttachmentsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetAttachments")
		}
		return qGetAttachmentsHandler(ctx, m)
	case *query.GetBillingState:
		if qGetBillingStateHandler == nil {
			return fmt.Errorf("handler not registered: query.GetBillingState")
		}
		return qGetBillingStateHandler(ctx, m)
	case *query.GetBillingSubscription:
		if qGetBillingSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: query.GetBillingSubscription")
		}
		return qGetBillingSubscriptionHandler(ctx, m)
	case *query.GetBlobByKey:
		if qGetBlobByKeyHandler == nil {
			return fmt.Errorf("handler not registered: query.GetBlobByKey")
		}
		return qGetBlobByKeyHandler(ctx, m)
	case *query.GetCannedResponseByID:
		if qGetCannedResponseByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetCannedResponseByID")
		}
		return qGetCannedResponseByIDHandler(ctx, m)
	case *query.GetCommentByID:
		if qGetCommentByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetCommentByID")
		}
		return qGetCommentByIDHandler(ctx, m)
	case *query.GetCommentsByPage:
		if qGetCommentsByPageHandler == nil {
			return fmt.Errorf("handler not registered: query.GetCommentsByPage")
		}
		return qGetCommentsByPageHandler(ctx, m)
	case *query.GetCommentsByPost:
		if qGetCommentsByPostHandler == nil {
			return fmt.Errorf("handler not registered: query.GetCommentsByPost")
		}
		return qGetCommentsByPostHandler(ctx, m)
	case *query.GetCurrentUserSettings:
		if qGetCurrentUserSettingsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetCurrentUserSettings")
		}
		return qGetCurrentUserSettingsHandler(ctx, m)
	case *query.GetCustomOAuthConfigByProvider:
		if qGetCustomOAuthConfigByProviderHandler == nil {
			return fmt.Errorf("handler not registered: query.GetCustomOAuthConfigByProvider")
		}
		return qGetCustomOAuthConfigByProviderHandler(ctx, m)
	case *query.GetFirstTenant:
		if qGetFirstTenantHandler == nil {
			return fmt.Errorf("handler not registered: query.GetFirstTenant")
		}
		return qGetFirstTenantHandler(ctx, m)
	case *query.GetImageFile:
		if qGetImageFileHandler == nil {
			return fmt.Errorf("handler not registered: query.GetImageFile")
		}
		return qGetImageFileHandler(ctx, m)
	case *query.GetNameFromBlobKey:
		if qGetNameFromBlobKeyHandler == nil {
			return fmt.Errorf("handler not registered: query.GetNameFromBlobKey")
		}
		return qGetNameFromBlobKeyHandler(ctx, m)
	case *query.GetNavigationLinks:
		if qGetNavigationLinksHandler == nil {
			return fmt.Errorf("handler not registered: query.GetNavigationLinks")
		}
		return qGetNavigationLinksHandler(ctx, m)
	case *query.GetNotificationByID:
		if qGetNotificationByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetNotificationByID")
		}
		return qGetNotificationByIDHandler(ctx, m)
	case *query.GetOAuthAuthorizationURL:
		if qGetOAuthAuthorizationURLHandler == nil {
			return fmt.Errorf("handler not registered: query.GetOAuthAuthorizationURL")
		}
		return qGetOAuthAuthorizationURLHandler(ctx, m)
	case *query.GetOAuthProfile:
		if qGetOAuthProfileHandler == nil {
			return fmt.Errorf("handler not registered: query.GetOAuthProfile")
		}
		return qGetOAuthProfileHandler(ctx, m)
	case *query.GetOAuthRawProfile:
		if qGetOAuthRawProfileHandler == nil {
			return fmt.Errorf("handler not registered: query.GetOAuthRawProfile")
		}
		return qGetOAuthRawProfileHandler(ctx, m)
	case *query.GetPageByID:
		if qGetPageByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageByID")
		}
		return qGetPageByIDHandler(ctx, m)
	case *query.GetPageBySlug:
		if qGetPageBySlugHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageBySlug")
		}
		return qGetPageBySlugHandler(ctx, m)
	case *query.GetPageDraft:
		if qGetPageDraftHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageDraft")
		}
		return qGetPageDraftHandler(ctx, m)
	case *query.GetPageSubscribers:
		if qGetPageSubscribersHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageSubscribers")
		}
		return qGetPageSubscribersHandler(ctx, m)
	case *query.GetPageTagByID:
		if qGetPageTagByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageTagByID")
		}
		return qGetPageTagByIDHandler(ctx, m)
	case *query.GetPageTags:
		if qGetPageTagsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageTags")
		}
		return qGetPageTagsHandler(ctx, m)
	case *query.GetPageTopicByID:
		if qGetPageTopicByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageTopicByID")
		}
		return qGetPageTopicByIDHandler(ctx, m)
	case *query.GetPageTopics:
		if qGetPageTopicsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPageTopics")
		}
		return qGetPageTopicsHandler(ctx, m)
	case *query.GetPostByID:
		if qGetPostByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPostByID")
		}
		return qGetPostByIDHandler(ctx, m)
	case *query.GetPostByNumber:
		if qGetPostByNumberHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPostByNumber")
		}
		return qGetPostByNumberHandler(ctx, m)
	case *query.GetPostBySlug:
		if qGetPostBySlugHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPostBySlug")
		}
		return qGetPostBySlugHandler(ctx, m)
	case *query.GetPostsByIDs:
		if qGetPostsByIDsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPostsByIDs")
		}
		return qGetPostsByIDsHandler(ctx, m)
	case *query.GetPrunableFiles:
		if qGetPrunableFilesHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPrunableFiles")
		}
		return qGetPrunableFilesHandler(ctx, m)
	case *query.GetPushSubscriptionsByUser:
		if qGetPushSubscriptionsByUserHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPushSubscriptionsByUser")
		}
		return qGetPushSubscriptionsByUserHandler(ctx, m)
	case *query.GetPushSubscriptionsByUsers:
		if qGetPushSubscriptionsByUsersHandler == nil {
			return fmt.Errorf("handler not registered: query.GetPushSubscriptionsByUsers")
		}
		return qGetPushSubscriptionsByUsersHandler(ctx, m)
	case *query.GetReportByID:
		if qGetReportByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetReportByID")
		}
		return qGetReportByIDHandler(ctx, m)
	case *query.GetReportReasons:
		if qGetReportReasonsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetReportReasons")
		}
		return qGetReportReasonsHandler(ctx, m)
	case *query.GetSystemSettings:
		if qGetSystemSettingsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetSystemSettings")
		}
		return qGetSystemSettingsHandler(ctx, m)
	case *query.GetTagBySlug:
		if qGetTagBySlugHandler == nil {
			return fmt.Errorf("handler not registered: query.GetTagBySlug")
		}
		return qGetTagBySlugHandler(ctx, m)
	case *query.GetTenantByDomain:
		if qGetTenantByDomainHandler == nil {
			return fmt.Errorf("handler not registered: query.GetTenantByDomain")
		}
		return qGetTenantByDomainHandler(ctx, m)
	case *query.GetTenantProfanityWords:
		if qGetTenantProfanityWordsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetTenantProfanityWords")
		}
		return qGetTenantProfanityWordsHandler(ctx, m)
	case *query.GetTrialingTenantContacts:
		if qGetTrialingTenantContactsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetTrialingTenantContacts")
		}
		return qGetTrialingTenantContactsHandler(ctx, m)
	case *query.GetUserByAPIKey:
		if qGetUserByAPIKeyHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserByAPIKey")
		}
		return qGetUserByAPIKeyHandler(ctx, m)
	case *query.GetUserByEmail:
		if qGetUserByEmailHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserByEmail")
		}
		return qGetUserByEmailHandler(ctx, m)
	case *query.GetUserByID:
		if qGetUserByIDHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserByID")
		}
		return qGetUserByIDHandler(ctx, m)
	case *query.GetUserByProvider:
		if qGetUserByProviderHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserByProvider")
		}
		return qGetUserByProviderHandler(ctx, m)
	case *query.GetUserCommentCount:
		if qGetUserCommentCountHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserCommentCount")
		}
		return qGetUserCommentCountHandler(ctx, m)
	case *query.GetUserPostCount:
		if qGetUserPostCountHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserPostCount")
		}
		return qGetUserPostCountHandler(ctx, m)
	case *query.GetUserProfileStanding:
		if qGetUserProfileStandingHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserProfileStanding")
		}
		return qGetUserProfileStandingHandler(ctx, m)
	case *query.GetUserProfileStats:
		if qGetUserProfileStatsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserProfileStats")
		}
		return qGetUserProfileStatsHandler(ctx, m)
	case *query.GetUserReportedItemsOnPost:
		if qGetUserReportedItemsOnPostHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUserReportedItemsOnPost")
		}
		return qGetUserReportedItemsOnPostHandler(ctx, m)
	case *query.GetUsersByIDs:
		if qGetUsersByIDsHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUsersByIDs")
		}
		return qGetUsersByIDsHandler(ctx, m)
	case *query.GetUsersToNotify:
		if qGetUsersToNotifyHandler == nil {
			return fmt.Errorf("handler not registered: query.GetUsersToNotify")
		}
		return qGetUsersToNotifyHandler(ctx, m)
	case *query.GetVerificationByKey:
		if qGetVerificationByKeyHandler == nil {
			return fmt.Errorf("handler not registered: query.GetVerificationByKey")
		}
		return qGetVerificationByKeyHandler(ctx, m)
	case *query.GetWebhook:
		if qGetWebhookHandler == nil {
			return fmt.Errorf("handler not registered: query.GetWebhook")
		}
		return qGetWebhookHandler(ctx, m)
	case *query.HasPushSubscription:
		if qHasPushSubscriptionHandler == nil {
			return fmt.Errorf("handler not registered: query.HasPushSubscription")
		}
		return qHasPushSubscriptionHandler(ctx, m)
	case *query.HasUserReportedTarget:
		if qHasUserReportedTargetHandler == nil {
			return fmt.Errorf("handler not registered: query.HasUserReportedTarget")
		}
		return qHasUserReportedTargetHandler(ctx, m)
	case *query.IsCNAMEAvailable:
		if qIsCNAMEAvailableHandler == nil {
			return fmt.Errorf("handler not registered: query.IsCNAMEAvailable")
		}
		return qIsCNAMEAvailableHandler(ctx, m)
	case *query.IsImageFileInUse:
		if qIsImageFileInUseHandler == nil {
			return fmt.Errorf("handler not registered: query.IsImageFileInUse")
		}
		return qIsImageFileInUseHandler(ctx, m)
	case *query.IsSubdomainAvailable:
		if qIsSubdomainAvailableHandler == nil {
			return fmt.Errorf("handler not registered: query.IsSubdomainAvailable")
		}
		return qIsSubdomainAvailableHandler(ctx, m)
	case *query.ListActiveOAuthProviders:
		if qListActiveOAuthProvidersHandler == nil {
			return fmt.Errorf("handler not registered: query.ListActiveOAuthProviders")
		}
		return qListActiveOAuthProvidersHandler(ctx, m)
	case *query.ListActiveWebhooksByType:
		if qListActiveWebhooksByTypeHandler == nil {
			return fmt.Errorf("handler not registered: query.ListActiveWebhooksByType")
		}
		return qListActiveWebhooksByTypeHandler(ctx, m)
	case *query.ListAllOAuthProviders:
		if qListAllOAuthProvidersHandler == nil {
			return fmt.Errorf("handler not registered: query.ListAllOAuthProviders")
		}
		return qListAllOAuthProvidersHandler(ctx, m)
	case *query.ListAllReportReasons:
		if qListAllReportReasonsHandler == nil {
			return fmt.Errorf("handler not registered: query.ListAllReportReasons")
		}
		return qListAllReportReasonsHandler(ctx, m)
	case *query.ListAllWebhooks:
		if qListAllWebhooksHandler == nil {
			return fmt.Errorf("handler not registered: query.ListAllWebhooks")
		}
		return qListAllWebhooksHandler(ctx, m)
	case *query.ListAllWebhooksByType:
		if qListAllWebhooksByTypeHandler == nil {
			return fmt.Errorf("handler not registered: query.ListAllWebhooksByType")
		}
		return qListAllWebhooksByTypeHandler(ctx, m)
	case *query.ListBlobs:
		if qListBlobsHandler == nil {
			return fmt.Errorf("handler not registered: query.ListBlobs")
		}
		return qListBlobsHandler(ctx, m)
	case *query.ListCannedResponses:
		if qListCannedResponsesHandler == nil {
			return fmt.Errorf("handler not registered: query.ListCannedResponses")
		}
		return qListCannedResponsesHandler(ctx, m)
	case *query.ListCustomOAuthConfig:
		if qListCustomOAuthConfigHandler == nil {
			return fmt.Errorf("handler not registered: query.ListCustomOAuthConfig")
		}
		return qListCustomOAuthConfigHandler(ctx, m)
	case *query.ListImageFiles:
		if qListImageFilesHandler == nil {
			return fmt.Errorf("handler not registered: query.ListImageFiles")
		}
		return qListImageFilesHandler(ctx, m)
	case *query.ListPages:
		if qListPagesHandler == nil {
			return fmt.Errorf("handler not registered: query.ListPages")
		}
		return qListPagesHandler(ctx, m)
	case *query.ListPostVotes:
		if qListPostVotesHandler == nil {
			return fmt.Errorf("handler not registered: query.ListPostVotes")
		}
		return qListPostVotesHandler(ctx, m)
	case *query.ListReports:
		if qListReportsHandler == nil {
			return fmt.Errorf("handler not registered: query.ListReports")
		}
		return qListReportsHandler(ctx, m)
	case *query.MarkWebhookAsFailed:
		if qMarkWebhookAsFailedHandler == nil {
			return fmt.Errorf("handler not registered: query.MarkWebhookAsFailed")
		}
		return qMarkWebhookAsFailedHandler(ctx, m)
	case *query.PostIsReferenced:
		if qPostIsReferencedHandler == nil {
			return fmt.Errorf("handler not registered: query.PostIsReferenced")
		}
		return qPostIsReferencedHandler(ctx, m)
	case *query.SearchPosts:
		if qSearchPostsHandler == nil {
			return fmt.Errorf("handler not registered: query.SearchPosts")
		}
		return qSearchPostsHandler(ctx, m)
	case *query.SearchUserContent:
		if qSearchUserContentHandler == nil {
			return fmt.Errorf("handler not registered: query.SearchUserContent")
		}
		return qSearchUserContentHandler(ctx, m)
	case *query.UserSubscribedTo:
		if qUserSubscribedToHandler == nil {
			return fmt.Errorf("handler not registered: query.UserSubscribedTo")
		}
		return qUserSubscribedToHandler(ctx, m)
	case *query.UserSubscribedToPage:
		if qUserSubscribedToPageHandler == nil {
			return fmt.Errorf("handler not registered: query.UserSubscribedToPage")
		}
		return qUserSubscribedToPageHandler(ctx, m)
	default:
		return fmt.Errorf("no typed handler for message type: %T", msg)
	}
}
